### ISSUE TITLE
Robot is unbalanced

### ISSUE THREAD

**Issue by Richp16** [EliteHaxy/FTCGithubWebhook#6]
There is more weight on one side of the robot, so it turns, even if we program it to go straight forward. We can either use the IMU (inertial measurement unit), or we can add a counterweight.

**Comment by abkatyal** [comment]
OK, that sounds good. How did the countereweight stuff work out?

**Comment by Richp16** [comment]
It was never the weight that was the problem. The motor configurations were mixed up.              :|
